### ISSUE TITLE
xcelium simulator

### ISSUE THREAD

**Issue by sfjiang-astri** [taichi-ishitani/tvip-axi#21]
Hi Taichi,
![image](https://user-images.githubusercontent.com/69237646/96068341-6544ed80-0ece-11eb-9e58-53e5fefa6558.png)

how can i use this option?
thanks

**Comment by taichi-ishitani** [comment]
You don't need to add `-warn_multiple_driver` option to `make` command.

**Comment by taichi-ishitani** [comment]
This is a compile option of `xrun` command.
You can add this option to `xrun` command to avoid `*E,ICDCBA` error.

**Comment by sfjiang-astri** [comment]
Hi Taichi,
some *E,ICDCBA error occurs when i use make command only.
![image](https://user-images.githubusercontent.com/69237646/96071781-69c0d480-0ed5-11eb-99f1-5a636988ceb5.png)

**Comment by taichi-ishitani** [comment]
Can you apply following patch to `sample/work/xcelim.mk` and try again?

```patch
index 5cbb274..4549f0c 100644
--- a/sample/work/xcelium.mk
+++ b/sample/work/xcelium.mk
@@ -12,6 +12,7 @@ XMELAB_ARGS   += -uvmhome CDNS-1.1d
 XMELAB_ARGS    += -uvmnoautocompile
 XMELAB_ARGS    += -timescale 1ns/1ps
 XMELAB_ARGs    += -newperf
+XMELAB_ARGS    += -warn_multiple_driver
 XMELAB_ARGS    += -top worklib.top
 XMELAB_ARGS    += -l xmelab.log
```

**Comment by sfjiang-astri** [comment]
Hi Taichi,

The problem solved after following your link.

thanks and regards

**Comment by sfjiang-astri** [comment]
Hi Taichi,
which options  should I insert in the makefile if i want to dump the waveform of the test?

thanks

**Comment by taichi-ishitani** [comment]
I think you need to insert following commands for waveform dumping.
https://github.com/taichi-ishitani/tnoc/blob/c16b918b3247874d754a15d9a2b2eb5d911e042c/sim/common/xcelium.mk#L78

**Comment by sfjiang-astri** [comment]
![image](https://user-images.githubusercontent.com/69237646/96108554-4bc49580-0f10-11eb-8efb-dfd480682388.png)

I insert the options from line 42 to 57 in the xcelium.mk shown in the figure.
while I cannot dump the waveform in simvision after running the command
 'make SIMULATOR=xcelium default DUMP=on GUI=on'

**Comment by taichi-ishitani** [comment]
```
$ make clean; make SIMULATOR=xcelium DUMP=shm
```

This is correct command.

**Comment by sfjiang-astri** [comment]
Thanks Taichi,
while it seems the clock didnot starts to work.
![image](https://user-images.githubusercontent.com/69237646/96109669-77944b00-0f11-11eb-8790-462e2924daa0.png)
any options should I insert when running the command.

**Comment by taichi-ishitani** [comment]
I think this option may be needed.
https://github.com/taichi-ishitani/tnoc/blob/c16b918b3247874d754a15d9a2b2eb5d911e042c/sim/common/xcelium.mk#L59
But I'm not sure.

**Comment by taichi-ishitani** [comment]
@sfjiang-astri ,
Did your simulation trial work well?

**Comment by sfjiang-astri** [comment]
> @sfjiang-astri ,
> Did your simulation trial work well?

Hi Taichi,
thanks for your comment, the simulation works well.
And I want to use this tvip-axi as a vip in my verification project.

thanks
sfjiang

**Comment by taichi-ishitani** [comment]
> thanks for your comment, the simulation works well.

Good!

> And I want to use this tvip-axi as a vip in my verification project.

OK, no problem.
Please feel free to ask question, feedback, feature request if you have :)

**Comment by taichi-ishitani** [comment]
@sfjiang-astri 
Did `-run` option resolve the problem simulation does not start?

**Comment by sfjiang-astri** [comment]
> @sfjiang-astri
> Did `-run` option resolve the problem simulation does not start?

Yes, It works.

**Comment by taichi-ishitani** [comment]
Thanks!

**Comment by sfjiang-astri** [comment]
> Thanks!

by the way, what is the meaning for  "-warn_multiple_driver" when using the xrun simulator?

thanks

**Comment by taichi-ishitani** [comment]
For SystemVerilog, assignment having multiple drivers such as the following is not allowed and `xrun` will raise `*E,ICDCBA` error.

```systemverilog
byte a, b, c;
always_comb a = b; //driver 1
always_comb a = c; //driver 2
```

The `-warn_multiple_driver` option is to change severity of `*E,ICDCBA` error to warning.

In case of the sample TB, I don't know why `*E,ICDCBA` error is happened.
I'm not familiar with Xcelium because I use VCS mainly so I use `-warn_multiple_driver` option to ignore `*E,ICDCBA` error.

**Comment by sfjiang-astri** [comment]
I see. So it is used to change the *E, ICDCBA error to the warning.
thanks and regards
