### ISSUE TITLE
feature comparison to commercial VIPs 

### ISSUE THREAD

**Issue by simdream** [taichi-ishitani/tvip-axi#26]
For your UVM based AXI VIP, if we could compare with the those commercially provided from Cadence or Synopsys, how much percentage of the features are covered? 

Your VIP is the only one available in open source and extremely impressive!

**Comment by taichi-ishitani** [comment]
tvip-axi has very limited features.

* It's just BFM. No checkers/SVAs/covergroups are implemented.
* `INC` burst type is only supported.
* Some AXI signals are not implemented.
    * eg: axlock/axcache/axprot/axregion/axuser
* AXI ACE is not supported.
