### ISSUE TITLE
Path example for replacing `uvm_do* macros 

### ISSUE THREAD

**Issue by octavsly** [taichi-ishitani/tvip-axi#51]
[no_uvm_do.patch](https://github.com/taichi-ishitani/tvip-axi/files/13874642/no_uvm_do.patch)

patch for removing the `uvm_do macros since they are not supported in newer UVM versions.

**Comment by taichi-ishitani** [comment]
Hi @octavsly ,
Thank you for your information.
I've fixed errors related to UVM update by this commit.
e31e9f54db7b7675ea16b0d7fa190c8e1fd62a98
