### ISSUE TITLE
master_to_vip_slave

### ISSUE THREAD

**Issue by GreenStealCode** [taichi-ishitani/tvip-axi#57]
Hi, taichi
  I'm new to UVM.I want to know that how could I use this repo building a"master to VIP slave" environment to test my AXI master.

**Comment by taichi-ishitani** [comment]
See the sample TB.
https://github.com/taichi-ishitani/tvip-axi/tree/master/sample

**Comment by GreenStealCode** [comment]
Yes, I read the sample before, but I still confused about how to replace the sample's vip master with my dut master.
