### ISSUE TITLE
Show syntax errors

### ISSUE THREAD

**Issue by PSability** [taichi-ishitani/tvip-axi#60]
[xmvlog.log](https://github.com/user-attachments/files/18240086/xmvlog.log)

Hundreds of syntax errors occurred after running the command "make SIMULATOR=xcelium". 
Obviously  this is not problems with your code, so could you please tell me how these errors are caused.? I've upload the log file. Thank you!

**Comment by PSability** [comment]
I control a server machine(cadense palladium Z1) remotely, and that server cannot access to the outside website, so I run the 'setup_submodules.sh' file in my windows computer under linux environment, finally i copy and paste the generated folders 'tue' and 'tvip-common' to my server.Does it cause any problem? thanks.
in addition, my xcelium version is 20.03

**Comment by taichi-ishitani** [comment]
I cannot use Xcerium simulator so I have no idea.
You should ask Cadenae support.

**Comment by PSability** [comment]
thank you

> I cannot use Xcerium simulator so I have no idea. You should ask Cadenae support.
